name: CI-CD Basic (refactorisé)

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test-and-install.yml

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application
        run: echo "Deploying application to server..."
