name: production workflow
on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.DATABASE_URL }}
    steps:
      - run: |
          echo Deploy to production
